seed: 21

simulator:
  name: "bimodal_gaussian"
  params:
    sigma_noise: 0.1

prior:
  name: "uniform"
  params:
    low: -10.0
    high: 10.0
    dim: 2

observation:
  name: "zeros"
  params:
    nof_obs: 1
    dim_y: 2

inference:
  name: "npe_a_single_round"

  train_and_sample:
    budget: 1000
    nof_samples: 100
